name = "UniKrypToks"
uuid = "fa8da494-afdd-4eb3-b76d-fcf46394284c"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"

[compat]
FixedPointDecimals = "0.6.3"
julia = "1.6.7"
